# Author: Russell Williams
# Email: russell.d.williams@gmail.com
# Copyright 2016

# Generates heroic couplets using sonnet.py, rates them using a model
# generated by rate.py, and posts the best ones to Twitter.

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.


import sonnet as snt
from tensorflow.contrib import skflow
import model
from model import ModelConfig
import logging
import tweepy
from secrets import *
import datetime
import time
import pickle

logger = logging.getLogger(__name__)
logging.basicConfig(
    level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# Generate couplets:
vocab = snt.Vocab()
sw = snt.SonnetWriter(vocab)
sw.load_templates("line_templates.csv")

vocab.add_random_collections(2)
couplets = snt.HeroicCouplets(12)

sw.new_poem(couplets)

# Load rating model:
logging.info("Loading model config...")
with open("models/model_config_20160513.pickle") as f:
    config = pickle.load(f)
logging.info("Done.")
logging.info("Loading humanity model...")
hum_classifier = skflow.TensorFlowEstimator.restore("models/hum_classifier_20160513")
logging.info("Done.")
logging.info("Loading interest model...")
int_classifier = skflow.TensorFlowEstimator.restore("models/int_classifier_20160513")
logging.info("Done.")


seqs = [model.convert_to_sequence(section) for section in couplets.sections]
x = config.transform_seqs(seqs)


def sum_ratings(probs):
    return sum([prob * rating for prob, rating in zip(probs, range(4))])

# Rate each couplet and sort by ratings:
hum_ratings = [sum_ratings(probs) * 3 for probs in hum_classifier.predict_proba(x)]
int_ratings = [sum_ratings(probs) * 3 for probs in int_classifier.predict_proba(x)]

for section, hum_rat, int_rat in zip(couplets.sections, hum_ratings, int_ratings):
    section.human = hum_rat
    section.interesting = int_rat

timestamp = datetime.datetime.now()
filename = "unrated_couplet_batch_{}.pickle".format(timestamp.strftime("%Y%m%d-%H%M"))
with open(filename, "wb") as f:
    pickle.dump(couplets, f)

couplets.sections.sort(key=lambda x: x.human * x.interesting)
couplets.sections.reverse()

# Tweet 2 best rated couplets
auth = tweepy.OAuthHandler(C_KEY, C_SECRET)
auth.set_access_token(A_TOKEN, A_TOKEN_SECRET)
api = tweepy.API(auth)


NUM_TO_TWEET = 2

for couplet in couplets.sections[:NUM_TO_TWEET]:
    api.update_status(couplet.text)
    time.sleep(30)