# Author: Russell Williams
# Email: russell.d.williams@gmail.com
# Copyright 2016

# Gathers user ratings, section-by-section, of a pickled file of
# poems generated by sonnet.py

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.



import pickle
import argparse
import sys


def parse_args(args):
    parser = argparse.ArgumentParser(
        description="Gets user ratings for sonnets in an input pickle")
    parser.add_argument("--input",
                        "-i",
                        required=True,
                        help="Input filename (Required)")
    parser.add_argument("--output",
                        "-o",
                        required = True,
                        help = "Output filename (Required)")
    parsed_args = parser.parse_args(args)
    return vars(parsed_args)

def rate_section(section):
    print section.text
    print "\n"
    section.get_user_rating()

def rate_sonnet(sonnet):
    for section in sonnet.sections:
        rate_section(section)


def main(args):
    with open(args["input"], "r") as f:
        all_sonnets = pickle.load(f)
    unrated_sonnets = [sonnet for sonnet in all_sonnets if not sonnet.sections[0].interesting]
    rated_sonnets = [sonnet for sonnet in all_sonnets if sonnet.sections[0].interesting]
    for sonnet in unrated_sonnets:
        rate_sonnet(sonnet)

    with open(args["output"], "wb") as f:
        pickle.dump(rated_sonnets, f)

if __name__ == "__main__":
    args = parse_args(sys.argv[1:])
    main(args)